### ISSUE TITLE
구매 참여 기능 구현

### ISSUE THREAD

**Issue by mgunho18** [f-lab-edu/buy-with-me#12]
## Description
사용자는 다른 사람이 작성한 게시글을 읽고 구매 참여 버튼을 눌러 공동구매에 참여할 수 있다.

## Todo
- [ ] 구매 참여 / 취소 API 개발
- [ ] Controller, Service, Repository layer의 유닛 테스트 작성
- [ ] JPA Pessimistic Write mode를 이용한 동시성 처리
